<?php
/**
 * The template for displaying the footer
 *
 * Contains the closing of the #content div and all content after.
 *
 * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
 *
 * @package WordPress
 * @subpackage Twenty_Seventeen
 * @since 1.0
 * @version 1.0
 */

?>
<footer>
	<div>
		<img src="/img/sign_foot.png" alt="logo">
		<p>Copyright 2017 Risako Yamada. All Rights Reserved.</p>
	</div>
</footer>
</body>
</html>
<!-- Dynamic page generated in 0.146 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-04-18 03:44:10 -->

<!-- super cache -->
